/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author kferens
 */
public class GUI extends javax.swing.JFrame implements userinterface.UserInterface{

    /**
     * Creates new form GUI
     */
    String port = "";
    usercommandhandler.UserCommandHandler myUserCommandHandler;
    public GUI() {
        initComponents();
    }

    public void update(String theResult) {
        messagesTextArea.append(theResult + "\n");
    }

    public void setCommand(usercommandhandler.UserCommandHandler myUserCommandHandler) {
        this.myUserCommandHandler = myUserCommandHandler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPortLabel = new javax.swing.JLabel();
        setPortTextField = new javax.swing.JTextField();
        setPortButton = new javax.swing.JButton();
        startServerSocketLabel = new javax.swing.JLabel();
        startServerSocketToggleButton = new javax.swing.JToggleButton();
        startListeningLabel = new javax.swing.JLabel();
        startListeningToggleButton = new javax.swing.JToggleButton();
        messagesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagesTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setPortLabel.setText("Set Port");

        setPortButton.setText("Update");
        setPortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPortButtonActionPerformed(evt);
            }
        });

        startServerSocketLabel.setText("Start Server Socket");

        startServerSocketToggleButton.setText("Start");
        startServerSocketToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerSocketToggleButtonActionPerformed(evt);
            }
        });

        startListeningLabel.setText("Start Listening");

        startListeningToggleButton.setText("Start");
        startListeningToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startListeningToggleButtonActionPerformed(evt);
            }
        });

        messagesLabel.setText("Messages");

        messagesTextArea.setColumns(20);
        messagesTextArea.setRows(5);
        jScrollPane1.setViewportView(messagesTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(messagesLabel)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(startServerSocketLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(setPortLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(setPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(startListeningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setPortButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(startServerSocketToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startListeningToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setPortLabel)
                    .addComponent(setPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setPortButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startServerSocketLabel)
                    .addComponent(startServerSocketToggleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startListeningLabel)
                    .addComponent(startListeningToggleButton))
                .addGap(18, 18, 18)
                .addComponent(messagesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setPortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPortButtonActionPerformed
        port = setPortTextField.getText();
        //messagesTextArea.append("The port number has been set to " + port + "\n");
        myUserCommandHandler.handleUserCommand("3 " + port);
    }//GEN-LAST:event_setPortButtonActionPerformed

    private void startServerSocketToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServerSocketToggleButtonActionPerformed
        if(startServerSocketToggleButton.isSelected()==true) {
            messagesTextArea.append("Starting server socket @ port " + port + "\n");
            startServerSocketToggleButton.setText("Stop");
            myUserCommandHandler.handleUserCommand("6");
        }
        else {
            messagesTextArea.append("Stopping server socket @ port " + port + "\n");
            startServerSocketToggleButton.setText("Start");
        }
        
    }//GEN-LAST:event_startServerSocketToggleButtonActionPerformed

    private void startListeningToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startListeningToggleButtonActionPerformed
        if(startListeningToggleButton.isSelected()==true) {
            messagesTextArea.append("Starting listening @ port " + port + "\n");
            startListeningToggleButton.setText("Stop");
            myUserCommandHandler.handleUserCommand("2");
        }
        else {
            messagesTextArea.append("Stopping listening @ port " + port + "\n");
            startListeningToggleButton.setText("Start");
        }
    }//GEN-LAST:event_startListeningToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messagesLabel;
    private javax.swing.JTextArea messagesTextArea;
    private javax.swing.JButton setPortButton;
    private javax.swing.JLabel setPortLabel;
    private javax.swing.JTextField setPortTextField;
    private javax.swing.JLabel startListeningLabel;
    private javax.swing.JToggleButton startListeningToggleButton;
    private javax.swing.JLabel startServerSocketLabel;
    private javax.swing.JToggleButton startServerSocketToggleButton;
    // End of variables declaration//GEN-END:variables
}
