/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import usercommandhandler.UserCommandHandler;

/**
 *
 * @author Mohammad ELsayyed
 */
public class Gui extends javax.swing.JFrame implements userinterface.UserInterface {

    private int led1Toggle = 1;
    private int led2Toggle = 1;
    private int led3Toggle = 1;
    private int led4Toggle = 1;
    private int pb1Toggle  = 1;
    private int pb2Toggle  = 1;
    private int pb3Toggle  = 1;
    private int pbThemeToggle =1;
    usercommandhandler.UserCommandHandler myUserCommandHandler;
    

    /**
     * Creates new form clientGUI
     */
    public Gui() {
        initComponents();
    }

        @Override
    public void update(String theMessage) {
      serverMessageTextArea.setText(theMessage);
    }
    
    public void setCommandHandler(usercommandhandler.UserCommandHandler myUserCommandHandler) {
        this.myUserCommandHandler = myUserCommandHandler;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectButton = new javax.swing.JButton();
        getTimeButton = new javax.swing.JButton();
        disconnectButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        setLEDLabel = new javax.swing.JLabel();
        LED1Label = new javax.swing.JLabel();
        LED2Label = new javax.swing.JLabel();
        LED3Label = new javax.swing.JLabel();
        LED4Label = new javax.swing.JLabel();
        led1_button = new javax.swing.JButton();
        led2_button = new javax.swing.JButton();
        led3_button = new javax.swing.JButton();
        led4_button = new javax.swing.JButton();
        pbLabel = new javax.swing.JLabel();
        pb1Label = new javax.swing.JLabel();
        pb2Label = new javax.swing.JLabel();
        pb3Label = new javax.swing.JLabel();
        themeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        serverMessageTextArea = new javax.swing.JTextArea();
        serverMessageLabel = new javax.swing.JLabel();
        pb1TextField = new javax.swing.JTextField();
        pb2TextField = new javax.swing.JTextField();
        pb3TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        getTimeButton.setText("Get Time");
        getTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTimeButtonActionPerformed(evt);
            }
        });

        disconnectButton.setText("Disconnect");
        disconnectButton.setToolTipText("");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        setLEDLabel.setForeground(new java.awt.Color(255, 15, 70));
        setLEDLabel.setText("Set LEDs");

        LED1Label.setText("LED1");

        LED2Label.setText("LED2");

        LED3Label.setText("LED4");

        LED4Label.setText("LED3");

        led1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                led1_buttonActionPerformed(evt);
            }
        });

        led2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                led2_buttonActionPerformed(evt);
            }
        });

        led3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                led3_buttonActionPerformed(evt);
            }
        });

        led4_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                led4_buttonActionPerformed(evt);
            }
        });

        pbLabel.setForeground(new java.awt.Color(0, 0, 255));
        pbLabel.setText("Get PBs");

        pb1Label.setText("PB1");
        pb1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pb1LabelMouseClicked(evt);
            }
        });

        pb2Label.setText("PB2");
        pb2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pb2LabelMouseClicked(evt);
            }
        });

        pb3Label.setText("PB3");
        pb3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pb3LabelMouseClicked(evt);
            }
        });

        themeButton.setText("Theme: Day");
        themeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeButtonActionPerformed(evt);
            }
        });

        serverMessageTextArea.setColumns(20);
        serverMessageTextArea.setRows(5);
        jScrollPane2.setViewportView(serverMessageTextArea);

        serverMessageLabel.setText("Server Messages");

        pb1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb1TextFieldActionPerformed(evt);
            }
        });

        pb2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb2TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getTimeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setLEDLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LED4Label)
                                .addGap(18, 18, 18)
                                .addComponent(led3_button, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LED2Label)
                                .addGap(18, 18, 18)
                                .addComponent(led2_button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LED3Label)
                                .addGap(18, 18, 18)
                                .addComponent(led4_button, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LED1Label)
                                .addGap(18, 18, 18)
                                .addComponent(led1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pbLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(pb1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pb1TextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(pb2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pb2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pb3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pb3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(disconnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(themeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(serverMessageLabel)
                        .addGap(105, 105, 105))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {led1_button, led2_button, led3_button, led4_button});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setLEDLabel)
                            .addComponent(pbLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(led1_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LED1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pb1Label)
                                .addComponent(pb1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(led2_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LED2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(led3_button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LED4Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LED3Label)
                                    .addComponent(led4_button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pb2Label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pb2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pb3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pb3Label)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(serverMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton)
                    .addComponent(disconnectButton)
                    .addComponent(getTimeButton)
                    .addComponent(quitButton)
                    .addComponent(themeButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {led1_button, led2_button, led3_button, led4_button});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTimeButtonActionPerformed
        // TODO add your handling code here:
        serverMessageTextArea.append("Get a watch.\n");
    }//GEN-LAST:event_getTimeButtonActionPerformed

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        // TODO add your handling code here:
        serverMessageTextArea.append("Disconnection from server was successful.\n");
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
         serverMessageTextArea.append("Quiting the program.\n");
    }//GEN-LAST:event_quitButtonActionPerformed

    private void led2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_led2_buttonActionPerformed
        // TODO add your handling code here:
        if (led2Toggle == 1){
            led2_button.setBackground(Color.red);
            led2Toggle = 0;
        }
        else{
            led2_button.setBackground(Color.white);
            led2Toggle = 1;
        }
    }//GEN-LAST:event_led2_buttonActionPerformed

    private void led3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_led3_buttonActionPerformed
        // TODO add your handling code here:
        if (led3Toggle == 1){
            led3_button.setBackground(Color.red);
            led3Toggle = 0;
        }
        else{
            led3_button.setBackground(Color.white);
            led3Toggle = 1;
        }
    }//GEN-LAST:event_led3_buttonActionPerformed

    private void led4_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_led4_buttonActionPerformed
        // TODO add your handling code here:
        if (led4Toggle == 1){
            led4_button.setBackground(Color.red);
            led4Toggle = 0;
        }
        else{
            led4_button.setBackground(Color.white);
            led4Toggle = 1;
        }
    }//GEN-LAST:event_led4_buttonActionPerformed

    private void led1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_led1_buttonActionPerformed
        // TODO add your handling code here:
        if (led1Toggle == 1){
            led1_button.setBackground(Color.red);
            led1Toggle = 0;
        }
        else{
            led1_button.setBackground(Color.white);
            led1Toggle = 1;
        }
    }//GEN-LAST:event_led1_buttonActionPerformed

    private void pb1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pb1TextFieldActionPerformed

    private void pb2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pb2TextFieldActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        
        serverMessageTextArea.append("Connection to server was successful.\n");
        myUserCommandHandler.handleUserCommand("2");
    }//GEN-LAST:event_connectButtonActionPerformed

    private void pb1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pb1LabelMouseClicked
        // TODO add your handling code here:
        if (pb1Toggle == 1){
            pb1TextField.setForeground(Color.blue);
            pb1TextField.setText("Up");
            pb1Toggle = 0;
        }
        else{
            pb1TextField.setForeground(Color.blue);
            pb1TextField.setText("Down");
            pb1Toggle = 1;
        }
    }//GEN-LAST:event_pb1LabelMouseClicked

    private void pb2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pb2LabelMouseClicked
        // TODO add your handling code here:
        if (pb2Toggle == 1){
            pb2TextField.setForeground(Color.blue);
            pb2TextField.setText("Up");
            pb2Toggle = 0;
        }
        else{
            pb2TextField.setForeground(Color.blue);
            pb2TextField.setText("Down");
            pb2Toggle = 1;
        }
    }//GEN-LAST:event_pb2LabelMouseClicked

    private void pb3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pb3LabelMouseClicked
        // TODO add your handling code here:
        if (pb3Toggle == 1){
            pb3TextField.setForeground(Color.blue);
            pb3TextField.setText("Up");
            pb3Toggle = 0;
        }
        else{
            pb3TextField.setForeground(Color.blue);
            pb3TextField.setText("Down");
            pb3Toggle = 1;
        }
    }//GEN-LAST:event_pb3LabelMouseClicked

    private void themeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeButtonActionPerformed
        // TODO add your handling code here:
        if (pbThemeToggle == 0){
            themeButton.setForeground(Color.black);
            themeButton.setBackground(Color.LIGHT_GRAY);
            themeButton.setText("Theme: Day");
            pbThemeToggle = 1;
        }
        else{
            themeButton.setText("Theme: Night");
            themeButton.setForeground(Color.green);
            themeButton.setBackground(Color.black);
            pbThemeToggle = 0;
        }
    }//GEN-LAST:event_themeButtonActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Gui().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LED1Label;
    private javax.swing.JLabel LED2Label;
    private javax.swing.JLabel LED3Label;
    private javax.swing.JLabel LED4Label;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JButton getTimeButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton led1_button;
    private javax.swing.JButton led2_button;
    private javax.swing.JButton led3_button;
    private javax.swing.JButton led4_button;
    private javax.swing.JLabel pb1Label;
    private javax.swing.JTextField pb1TextField;
    private javax.swing.JLabel pb2Label;
    private javax.swing.JTextField pb2TextField;
    private javax.swing.JLabel pb3Label;
    private javax.swing.JTextField pb3TextField;
    private javax.swing.JLabel pbLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel serverMessageLabel;
    private javax.swing.JTextArea serverMessageTextArea;
    private javax.swing.JLabel setLEDLabel;
    private javax.swing.JButton themeButton;
    // End of variables declaration//GEN-END:variables

}
